version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  pre_build:
    commands:
      - echo "Login to CodeArtifact..."
      - aws codeartifact login --tool npm --repository npm-repo --domain demo-artifact --domain-owner 381492178574 --region ap-southeast-1
  build:
    commands:
      - npm install --verbose
      - npm build
cache:
  key: npm-$(codebuild-hash-files package-lock.json)
  paths:
    - "node_modules/**/*"
