version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
  build:
    commands:
      - npm install --verbose
cache:
  key: npm2-$(codebuild-hash-files package-lock.json)
  paths:
    - "node_modules/**/*"
